version: '2'
services:
    nginx:
        build: ./nginx
        volumes:
        - ./nginx/nginx/:/etc/nginx/
        ports:
        - "80:80"
        depends_on:
        - nodered
        - mqtt

    nodered:
        build: ./node-red
        ports:
        - "8200:8200"
        volumes:
        - ./node-red/src:/src
        - ./node-red/src/customNodes/node-red-contrib-svg-storage:/data/node_modules/node-red-contrib-svg-storage
        depends_on:
        - storage

    storage:
        build: ./storage-api
        ports:
        - "8100:8100"
        depends_on:
        - mongodb

    mongodb:
        image: mongo
        ports:
        - "27017:27017"
    
    mqtt:
        #build: ./mqtt
        image: jllopis/mosquitto
        volumes:
        - ./mqtt/mosquitto.d/:/etc/mosquitto.d/
        ports:
        - "9001:9001"
        - "1883:1883"