version: '2'
services:
    nodered:
        build: ./node-red
        ports:
        - "1880:1880"
        volumes:
        - ./node-red/src:/src

    mongodb:
        image: mongo
        ports:
        - "27017:27017"