version: '2'
services:
    nodered:
        build: ./node-red
        ports:
        - "1880:1880"
        volumes:
        - ./node-red/src:/src
        depends_on:
        - storage

    storage:
        build: ./storage-api
        ports:
        - "8100:8100"
        depends_on:
        - mongodb

    mongodb:
        image: mongo
        ports:
        - "27017:27017"