version: '2'
services:
    
    redbird:
        build: ./redbird
        volumes:
        - ./redbird/src:/src
        ports:
        - "80:80"
        depends_on:
        - nodered
        - mqtt

    nodered:
        build: ./node-red
        ports:
        - "8200:8200"
        volumes:
        - ./node-red/src:/src
        - ./node-red/src/customNodes/node-red-contrib-svg-storage:/data/node_modules/node-red-contrib-svg-storage
        depends_on:
        - storage

    storage:
        build: ./storage-api
        volumes:
        - ./storage-api/src:/src
        ports:
        - "8100:8100"
        depends_on:
        - mongodb

    projects-manager:
        build: ./projects-manager
        volumes:
        - ./projects-manager/src:/src
        ports:
        - "8300:8300"
        depends_on:
        - mongodb

    mongodb:
        image: mongo
        ports:
        - "27017:27017"
    
    mqtt:
        build: ./mqtt
        #image: jllopis/mosquitto
        volumes:
         - ./mqtt/:/mosquitto/config
        ports:
        - "9883:9883"
        - "9001:9001"
        - "1883:1883"